const data = {
	burgers: [
		{
			name: "Terbinafine",
			price: 5.83,
			description: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
			review: 316,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger",
			quantity: 10,
			calories: 260,
			fiber: 57,
			protein: 29,
			carbs: 36,
		},
		{
			name: "Triclosan",
			price: 13.64,
			description:
				"Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
			review: 47,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/cheeseburger",
			quantity: 6,
			calories: 211,
			fiber: 19,
			protein: 38,
			carbs: 46,
		},
		{
			name: "Amlodipine",
			price: 9.41,
			description:
				"Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
			review: 152,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/banquet",
			quantity: 7,
			calories: 240,
			fiber: 35,
			protein: 28,
			carbs: 47,
		},
		{
			name: "Glyburide",
			price: 13.6,
			description:
				"Proin leo odio, porttitor _id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
			review: 127,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/sandwich",
			quantity: 3,
			calories: 203,
			fiber: 21,
			protein: 24,
			carbs: 49,
		},
		{
			name: "Tapentadol",
			price: 9.25,
			description:
				"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
			review: 328,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/beef",
			quantity: 8,
			calories: 234,
			fiber: 56,
			protein: 20,
			carbs: 49,
		},
		{
			name: "Nafcillin",
			price: 6.99,
			description:
				"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
			review: 235,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/meat",
			quantity: 9,
			calories: 269,
			fiber: 35,
			protein: 16,
			carbs: 22,
		},
		{
			name: "Isopropyl",
			price: 13.19,
			description:
				"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
			review: 396,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/fish-burger",
			quantity: 5,
			calories: 211,
			fiber: 35,
			protein: 15,
			carbs: 26,
		},
		{
			name: "GLYCERIN",
			price: 7.63,
			description:
				"In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
			review: 426,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/tuna",
			quantity: 4,
			calories: 126,
			fiber: 23,
			protein: 21,
			carbs: 50,
		},
		{
			name: "Carvedilol",
			price: 13.22,
			description:
				"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
			review: 298,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/meat",
			quantity: 7,
			calories: 103,
			fiber: 17,
			protein: 26,
			carbs: 23,
		},
		{
			name: "Zincum",
			price: 6.71,
			description:
				"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus _id, turpis. Integer aliquet, convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.",
			review: 418,
			meal_img: "https://source.unsplash.com/1500x1000/?hamburger/busket",
			quantity: 9,
			calories: 256,
			fiber: 42,
			protein: 19,
			carbs: 50,
		},
	],
};
export default data;
